# Build settings
[build]
  publish = "./"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    # Enable HSTS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    # XSS protection
    X-Content-Type-Options = "nosniff"
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:; connect-src 'self' https:;"
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  output_path = "reports/lighthouse.html"
